services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    depends_on:
      - db
    # ローカルのカレントディレクトリをコンテナの/var/wwwにマウント
    volumes:
      - ./:/var/www
    # 80番ポートを割り当て
    ports:
      - ${WEB_PORT}:80

  db:
    # mysql:8.0イメージから構築
    image: mysql:8.0
    # 認証プラグインをmysql_native_passwordに設定
    volumes:
      - ./db-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    # .envで環境変数を管理
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    # 80番ポートを割り当て
    ports:
      - ${DB_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=cake
      - PMA_PASSWORD=cakepassword
    links:
      - db
    ports:
      - "9090:80"
